### 1. 로그인
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "name": "httpTestUser",
  "password": "password"
}

### 2. 로그아웃
GET http://localhost:8081/api/v1/auth/logout
