server:
  port: 8081

spring:
  config:
    import: classpath:privacy.yml
  datasource:
    driver-class-name: org.h2.Driver
    username: ${datasource.username}
    password: ${datasource.password}
    url: ${datasource.url}
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${oauth.google.id}
            client-secret: ${oauth.google.secret}
            scope:
              - email
              - profile

logging:
  file:
    path: ${log.path}

  level:
    root: info
    org.springframework.security: info
    spring:
      bbs: debug

jwt:
  header: Authorization
  secret: ${jwt.secret}
  access-token-duration: 1800000
  refresh-token-duration: 86400000

springdoc:
  version: v1.0.0
  packages-to-scan: spring.bbs
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /api-docs/json
    groups.enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8