INSERT INTO CATEGORY VALUES (1, 'string');
INSERT INTO CATEGORY VALUES (2, 'Java');
INSERT INTO CATEGORY VALUES (3, 'Spring');

-- INSERT INTO MEMBER(ID, NAME, OAUTH_NAME, PASSWORD, EMAIL, IS_ENABLED, CREATED_TIME, LAST_MODIFIED_TIME, AUTHORITY)
-- VALUES(1, 'test', null, 'password', 'asdf@asdf.asdf', true, null, null, 'ROLE_USER');
--
-- INSERT INTO POST(ID, AUTHOR_ID, CATEGORY_ID, TITLE, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME)
-- VALUES(1, 1, 1, 'testTitle1', 'test post1', null, null);
-- INSERT INTO POST(ID, AUTHOR_ID, CATEGORY_ID, TITLE, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME)
-- VALUES(2, 1, 1, 'testTitle2', 'test post2', null, null);
--
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (1, 1, 1, 'parentComment1', null, null, 1, 0, false, null);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (2, 1, 1, 'childComment1', null, null, 1, 1, false, 1);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (3, 1, 1, 'grandChildComment1', null, null, 1, 2, false, 2);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (4, 1, 1, 'childComment2', null, null, 1, 3, false, 1);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (9, 1, 1, 'parentComment2', null, null, 1, 0, false, null);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (10, 1, 1, 'childComment1', null, null, 9, 1, false, 1);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (11, 1, 1, 'grandChildComment1', null, null, 9, 2, false, 2);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (12, 1, 1, 'childComment2', null, null, 9, 3, false, 1);
--
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (5, 1, 2, 'parentComment', null, null, 1, 0, false, null);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (6, 1, 2, 'childComment1', null, null, 1, 1, false, 1);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (7, 1, 2, 'grandChildComment', null, null, 1, 2, false, 2);
-- INSERT INTO comment (ID, AUTHOR_ID, POST_ID, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME, GROUP_NUM, GROUP_ORDER, IS_DELETED, PARENT_COMMENT_ID)
-- values (8, 1, 2, 'childComment2', null, null, 1, 3, false, 1);
