INSERT INTO CATEGORY VALUES (1, 'string');
INSERT INTO CATEGORY VALUES (2, 'Java');
INSERT INTO CATEGORY VALUES (3, 'Spring');

INSERT INTO MEMBER(NAME, OAUTH_NAME, PASSWORD, EMAIL, IS_ENABLED, CREATED_TIME, LAST_MODIFIED_TIME, AUTHORITY)
VALUES('test', null, 'password', 'asdf@asdf.asdf', true, null, null, 'ROLE_USER');

INSERT INTO POST(AUTHOR_ID, CATEGORY_ID, TITLE, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME)
VALUES(1, 1, 'testTitle1', 'test post1', null, null);
INSERT INTO POST(AUTHOR_ID, CATEGORY_ID, TITLE, CONTENT, CREATED_TIME, LAST_MODIFIED_TIME)
VALUES(1, 1, 'testTitle2', 'test post2', null, null);