spring:
  config:
    import: classpath:privacy.yml
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  #  jpa:
  #    properties:
  #  #      hibernate:
  #  #        format_sql: true
  #  #        show_sql: true
  #  #        use_sql_comments: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}

logging:
  file:
    path: ${user.dir}/log
    name: ${user.dir}/log/bbs_log
  level:
    root: info
    spring:
      bbs: debug

jwt:
  secret: ${JWT_SECRET}
