spring:
  config:
    activate:
      on-profile: local
    import: classpath:privacy.yml
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_ID}
            client-secret: ${OAUTH_GOOGLE_SECRET}

logging:
  file:
    path: ${user.dir}/log

  level:
    root: info
    spring:
      bbs: debug

jwt:
  secret: ${JWT_SECRET}
